export const CONSTANTS = {
  WS_AUTH_TIMEOUT: 5000,
  WS_PING_INTERVAL: 5000,
  WS_PONG_TIMEOUT: 10000,
  RECONNECT_DELAYS: [1000, 2000, 4000, 8000, 30000],
  MAX_RECONNECT_ATTEMPTS: 10,
  STORAGE_KEYS: {
    LAST_CONNECTION: '@pocketpilot:last_connection',
    ALL_CONNECTIONS: '@pocketpilot:connections',
    PREFERENCES: '@pocketpilot:preferences',
  },
  MODELS: [
    'auto',
    'gemini-2.5-pro',
    'gemini-3.1-pro',
    'gpt-4.1',
    'gpt-5.3-codex',
    'claude-haiku-4.5',
    'gemini-3-flash',
    'gpt-4o',
    'gpt-5-mini',
    'gpt-5.2',
    'gpt-5.2-codex',
    'gpt-5.4-mini',
    'grok-code-fast-1',
    'raptor-mini',
  ],
  MODES: ['ask', 'agent', 'plan'],
  DEFAULT_MODE: 'ask',
  DEFAULT_MODEL: 'auto',
  COLORS: {
    background: '#1E1E1E',
    surface: '#2D2D2D',
    primary: '#C1440E',
    success: '#4CAF50',
    warning: '#FF9800',
    danger: '#F44336',
    text: '#FFFFFF',
    textMuted: '#888888',
    border: '#444444'
  }
};